version: "3.9"

services:
  backend:
    image: health-check-backend
    build:
      context: .
    env_file: .env
    volumes:
      - .:/usr/src/app/
    container_name: health-check-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    restart: always
    ports:
      - "8002:8002"
